font_size 14
font_family Adobe Source Han Sans

background #1e1e1e
foreground #b4befe

env GTK_IM_MODULE=fcitx
env QT_IM_MODULE=fcitx
env XMODIFIERS="im=fcitx"
env GLFW_IM_MODULE=ibus

window_padding_width 0
window_border_width 0

mouse_hide_wait 0
linux_display_server x11

cursor_shape beam
cursor #b7bdf8

map ctrl+shift+enter new_window
map ctrl+shift+t new_tab
map ctrl+shift+i launch --stdin-source=@last_cmd_output --type=clipboard
